name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies for linting
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Lint code
        run: ruff check .

      - name: Build Docker image for tests
        run: docker build -t interview_analyzer_test .

      - name: Run tests in Docker
        run: |
          docker run --rm \
            --env OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --env BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
            interview_analyzer_test \
            pytest --maxfail=1 --disable-warnings -q
