name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged
        ports:
          - 8000:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies for local tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff httpx

      - name: Lint with ruff
        run: ruff check .

      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Set up Docker Compose
        run: |
          docker compose build
          docker compose up -d

      - name: Wait for app to start
        run: |
          echo "Waiting for 5 seconds..."
          sleep 5

      - name: Run integration tests against Docker
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Tear down Docker Compose
        run: docker compose down

